### ISSUE TITLE
Missing preprocessed/ja.tsv

### ISSUE THREAD

**Issue by phochste** [Kyubyong/neural_japanese_transliterator#1]
I'm trying to run `annotate.py` but I seem to be missing some files in this project. Can you help me?

```(bash)
$ python annotate.py
Traceback (most recent call last):
  File "annotate.py", line 59, in <module>
    annotate()
  File "annotate.py", line 40, in annotate
    with codecs.open("preprocessed/ja.tsv", 'w', 'utf-8') as fout:
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'preprocessed/ja.tsv'
```

**Comment by Kyubyong** [comment]
Seems you didn't make the `preprocessed` folder.
I added a line: https://github.com/Kyubyong/neural_japanese_transliterator/blob/master/annotate.py#L40

**Comment by phochste** [comment]
Thanks!
